theme: jekyll-theme-clean-blog

title:              SOCAR Tech Blog
email:              recruit@socar.kr
description:        쏘카 기술 블로그
author:             SOCAR
baseurl:            ""
url:                "https://tech.socarcorp.kr"
exposeEmail:        false

# Social Profiles
twitter_username:   carnsharing
github_username:    # socar-inc
facebook_username:  socarsharing
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

disqus_url: https://tech.socarcorp.kr
disqus_id: socar-tech